#!/usr/bin/env zsh

# aliases file

alias ae='$EDITOR ~/.aliases'
alias ar='source ~/.aliases'

alias e='emacsclient'

alias copy='xclip -sel clipboard'
alias paste='xclip -sel clipboard -o'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

alias cl=clear

# alias for setting up my second display
alias connectdisp='xrandr --output eDP1 --auto --primary --output HDMI1 --auto --above eDP1'
