#!/bin/bash
# simple battery bar script for i3blocks
# the bar itself if made up of 5 unicode squares which become hollow of filled
# depending on the status of the battery.
# there are also colors that correspond with the status of the battery:

# red = your battery is less than 20% full, go charge it before you let it die :(
# orange = your battery is less than 40% full, you should start looking for a charger
# yellow = your battery is less than 60% full, just a friendly reminder that you have a battery
# white = your battey is less than 90% full, it is happy now 
# green = you are either charging your battery or it is above 90% full, good job :)

# and each color corresponds with a number of squares
# red = 1
# orange = 2
# yellow = 3
# white = 4 or 5
# green = 1-5

output=$(acpi)
actual=$(echo "$output" | awk '{ print $4 }' | cut -d, -f1)
status=$(echo "$output" | awk '{ print $3 }' | cut -d, -f1)
percentage=$(echo $actual | cut -d% -f1)
squares="⬛⬜⬜⬜⬜"
color="#FFFFFF"

if (( percentage > 0 && percentage < 20 )); then
  squares="⬛⬜⬜⬜⬜"
  color="#FF000" # red
elif (( percentage >= 20 && percentage < 40 )); then
  squares="⬛⬛⬜⬜⬜"
  color="#FFA500" # orange
elif (( percentage >= 40 && percentage < 60 )); then
  squares="⬛⬛⬛⬜⬜"
  color="#FFFF00" # yellow
elif (( percentage >= 60 && percentage < 80 )); then
  squares="⬛⬛⬛⬛⬜"
elif (( percentage >= 80 && percentage < 90 )); then
  squares="⬛⬛⬛⬛⬛"
elif (( percentage >= 90 )); then
  squares="⬛⬛⬛⬛⬛"
  color="#32CD32" # limegreen
fi


if [[ $status == "Charging" ]]; then
  color="#32CD32" # lime green
fi


echo "$actual $squares" # full text
echo "$actual" # short text
echo "$color" # color
